### ISSUE TITLE
Mixins in CSS modules

### ISSUE THREAD

**Issue by phts** [JulsD/React-study#8]
Regarding `src/app/components/Button/button.css`.

Classical CSS approach allows us to add multiple classes to an element. Like that:

```html
<div class="btn btn-active btn-disabled"></div>
```

CSS modules recommends to use **only one exported** css class in `className`. And mix CSS properties via [`composes` (click me)](https://github.com/css-modules/css-modules#composition). This works like mixins in Sass/Less.

So our button could look like:

```css
.root {
  ...
}

.primary {
  composes: root;    // <---------- here
  background-color: #f40612;
  color: #fff;
}
```

And then use only one exported `primary` class in `className` in the component.

```html
<button ... className={btnStyleMap[this.props.kind]}></button>
```

Re: #3
